CREATE SEQUENCE contract_id_seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE rno_seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tracking_num_seq MINVALUE 101 START WITH 101 INCREMENT BY 1;
